repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
  - chart: prometheus-community/kube-prometheus-stack
    name: prometheus-operator-k8s
    version: ~21.0.0
    disableValidation: true
    namespace: monitoring
